---
title: "Progress Memo 2"
subtitle: |
  | Final Project 
  | Data Science 1 with R (STAT 301-1)
author: "Nikole Montero Cervantes"

format:
  html:
    toc: true
    embed-resources: true
    
execute:
  echo: false
  warning: false

from: markdown+emoji 
---
  
::: {.callout-tip icon=false}

## Github Repo Link

[https://github.com/stat301-1-2023-fall/final-project-1-Nikole26.git](https://github.com/stat301-1-2023-fall/final-project-1-Nikole26.git)

:::

```{r}
#| echo: true
# Loading libraries 
library(tidyverse)
library(skimr)
library(DT)
library(stringr)

```

```{r}
# Loading data 
european_restaurants <- read_csv("data/tripadvisor_european_restaurants.csv")
```

# Data management
```{r}
skim_without_charts(european_restaurants)
```

```{r}
head(european_restaurants)
```

```{r}
# Adding a country code
countries_dict <- c('Austria' = 'AUT', 'Belgium' = 'BEL', 'Bulgaria' = 'BGR', 'Croatia' = 'HRV', 'Czech Republic' = 'CZE',
                    'Denmark' = 'DNK', 'England' = 'GBR', 'Finland' = 'FIN', 'France' = 'FRA', 'Germany' = 'DEU',
                    'Greece' = 'GRC', 'Hungary' = 'HUN', 'Ireland' = 'IRL', 'Italy' = 'ITA', 'Northern Ireland' = 'GBR',
                    'Poland' = 'POL', 'Portugal' = 'PRT', 'Romania' = 'ROU', 'Scotland' = 'GBR', 'Slovakia' = 'SVK',
                    'Spain' = 'ESP', 'Sweden' = 'SWE', 'The Netherlands' = 'NLD', 'Wales' = 'GBR')

# Displaying the code for each restaurant 
european_restaurants$country_code <- 
  ifelse(european_restaurants$country %in% names(countries_dict),                   countries_dict[european_restaurants$country],
         european_restaurants$country)   
```


```{r}
# Creating a new variable: average price
european_restaurants %>%
  mutate(
    minimum_range = as.numeric(str_extract(price_range, "\\d+(\\.\\d+)?")),
    maximum_range = as.numeric(str_extract_all(price_range, "\\d+(\\.\\d+)?") %>% sapply(function(x) x[2])),
    avg_price = (minimum_range + maximum_range) / 2
  ) %>%
  select(-c(minimum_range, maximum_range))

head(european_restaurants)
```
```{r}
european_restaurants %>%
  select(-avg_price) %>%
  summarise_all(~sum(is.na(.))) %>%
  filter(. > 0) %>%
  drop_na() %>%
  mutate_all(as.integer)
```

